apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarqube-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /sonarqube/
        backend:
          serviceName: sonarqube-sonarqube
          servicePort: 9000